"""What the deploy script and both demo agents share.

Why `genlayer_py` directly and not `gltest`
-------------------------------------------
`gltest` is a pytest harness. Its config layer only initialises under pytest —
`get_accounts()` outside it dies with `KeyError: None`
(`gltest_cli/config/types.py:150`) — and on studionet it mints **ten fresh
random accounts per process** (`gltest_cli/config/user.py:40`), so a seller
process and a buyer process could never share an identity through it. The demo
needs two stable keys across two scripts, so it reads them from `.env` and
drives `genlayer_py` itself.

Two consequences worth knowing, both good:

- **No ASCII shim.** The integration suite patches `encode_hex` because
  `factory.deploy()` ends in a schema fetch that passes the contract *source*
  to a function doing `.encode("ascii")`, and this contract holds 71 non-ASCII
  characters. Nothing here fetches a schema: the source is deployed as **bytes**
  and calls are made by name, so that whole failure mode is out of scope.
- **No Windows loader shim** either. That one is direct-mode only.
"""
import json
import os
import pathlib
import time

from genlayer_py import create_account, create_client
from genlayer_py.chains import studionet
from genlayer_py.types import TransactionStatus

REPO = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = REPO / "contracts" / "notch.py"

# Both fixtures, pinned to the commit that added the off-spec one. A *commit*
# SHA and never a branch: a branch URL serves whatever the file becomes, and the
# hash committed on-chain would drift out from under the evidence check. Verified
# live at this SHA: 200, 142b and 220b, digests matching the local bytes.
PINNED_SHA = "c3e34324a53f2a9a5ab9566c72b12e5a079f108e"
RAW_BASE = f"https://raw.githubusercontent.com/qFloppa/notch/{PINNED_SHA}/fixtures"

# 0.005 USDC per call at atto scale, the plan's figure.
ATTO_PER_CALL = 5 * 10**15
TAB_ID = "demo"

# The two receipts, and what each is for. `GOOD` substantiates a bill; `OFF_SPEC`
# hashes correctly and contradicts one, which is what puts the dispute on the
# model path instead of the hash short-circuit. Shared because the seller bills
# it and the buyer *finds* it — a second copy of either name would let the two
# sides disagree about which notch is the contested one.
GOOD = "receipt-good.json"
OFF_SPEC = "receipt-off-spec.json"

# Deploy-time policy, all three from the plan's Task 11.
BOND_ATTO = 10**18          # 1 GEN. Verified to post, credit and withdraw.
WINDOW_SECONDS = 3600
BASE_CREDIT_ATTO = 10 * 10**18   # 10 USDC

# What a fresh demo account is funded with. `fund_account` issues
# `sim_fundAccount`, which studionet accepts: its guard is
# `chain.id != localnet.id` and both ids are 61999. Needed for the bond, which
# is real attached value even though the network is gasless.
FUND_ATTO = 20 * 10**18

# Measured on studionet, not guessed: a write takes ~9-18s to reach ACCEPTED,
# and one in a few dozen stalls in PENDING for minutes before a leader picks it
# up. 120 retries x 3s = 6 minutes of patience per transaction, which is what
# separates "this network is slow" from "this transaction died".
WAIT_INTERVAL_MS = 3000
WAIT_RETRIES = 120

# Transport faults, which are not verdicts. Matched on the exception *text*
# because genlayer_py wraps every provider failure in a single `GenLayerError`
# ("Request to ... failed: ..."), so the class alone cannot tell a dropped socket
# from a reverted call. Narrow list on purpose — anything unrecognised is re-raised
# rather than retried.
TRANSPORT_ERRORS = (
    "RemoteDisconnected", "Connection aborted", "ConnectionError",
    "Read timed out", "ReadTimeout", "Max retries exceeded",
    "Connection reset", "ProtocolError", "Temporary failure in name resolution",
)
TRANSPORT_ATTEMPTS = 5
TRANSPORT_BACKOFF_S = 5


def accounts():
    """The seller and buyer identities, from `.env`.

    Generated by `deploy/deploy.py` and pasted into `.env`, so both agent
    processes address the same two parties. Absent keys are a hard error rather
    than a silent fresh account, which would open a tab nobody else can see.
    """
    load_env()
    missing = [k for k in ("SELLER_KEY", "BUYER_KEY") if not os.environ.get(k)]
    if missing:
        raise SystemExit(
            f"missing {', '.join(missing)} in .env -- run deploy/deploy.py first")
    return (create_account(os.environ["SELLER_KEY"]),
            create_account(os.environ["BUYER_KEY"]))


def load_env(path=None):
    """Minimal `.env` reader. `KEY=value`, `#` comments, no quoting rules.

    ponytail: `python-dotenv` is already installed as a gltest dependency, but
    this is nine lines and keeps the demo runnable without importing the test
    harness. Swap it for `dotenv.load_dotenv` if the format ever grows.
    """
    p = pathlib.Path(path) if path else REPO / ".env"
    if not p.exists():
        return
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())


def contract_address():
    load_env()
    addr = os.environ.get("NOTCH_ADDRESS")
    if not addr:
        raise SystemExit("missing NOTCH_ADDRESS in .env -- run deploy/deploy.py first")
    return addr


def client_for(account):
    return create_client(chain=studionet, account=account)


def failure_detail(receipt) -> str:
    """Why a write failed, from the fields that actually carry it.

    Never grep a receipt for short strings: the payload is hex-encoded contract
    source and matches any digit sequence you look for. A grep for `429` once
    produced a phantom rate-limit diagnosis in this project. Read the named
    fields.
    """
    lr = (receipt.get("consensus_data") or {}).get("leader_receipt") or [{}]
    lr = lr[0] if lr else {}
    parts = [f"execution_result={lr.get('execution_result')}",
             f"status={receipt.get('status_name')}",
             f"result={receipt.get('result_name')}"]
    stderr = (lr.get("genvm_result") or {}).get("stderr")
    if stderr:
        parts.append(f"stderr={str(stderr)[:300]}")
    return "  ".join(parts)


def succeeded(receipt) -> bool:
    """`execution_result == SUCCESS`, and nothing weaker.

    ACCEPTED and FINALIZED are lifecycle states, not success: a reverted call
    finalizes too, with every validator agreeing about the error, so a vote
    count alone looks healthy. Same check `gltest.assertions` makes, inlined so
    the agents do not import the test harness.
    """
    lr = (receipt.get("consensus_data") or {}).get("leader_receipt") or []
    return bool(lr) and lr[0].get("execution_result") == "SUCCESS"


class Notch:
    """A client bound to one contract and one signer, with waiting built in."""

    def __init__(self, client, address, account, label=""):
        self.client = client
        self.address = address
        self.account = account
        self.label = label

    def read(self, fn, *args):
        """A view call, retried on transport failure.

        Same reason as `write`: a dropped connection says nothing about the
        contract, and a view is idempotent so retrying it is free.
        """
        return self._transport_retry(
            lambda: self.client.read_contract(
                address=self.address, function_name=fn, args=list(args)),
            f"read {fn}")

    @staticmethod
    def _transport_retry(fn, label, attempts=TRANSPORT_ATTEMPTS):
        """Retry a call that failed *before* the network had an opinion.

        studionet drops connections occasionally — a 25-notch run hit
        `RemoteDisconnected('Remote end closed connection without response')`
        partway through, and a 200-notch run is 40 minutes of exposure to that.
        The endpoint was healthy seconds later, so the only thing that failed was
        the transport.

        Deliberately narrow. This retries the HTTP round trip, never a
        transaction the network actually judged: `GenLayerError` from a *receipt*
        (a revert, a failed verdict) is a real answer and is not retried, because
        re-sending a write the chain already accepted would bill a second notch.
        The wrapper is only applied where the call is idempotent — reads, and the
        `write_contract` submit step, which returns a hash rather than a result.
        """
        last = None
        for i in range(attempts):
            try:
                return fn()
            except Exception as e:
                text = f"{type(e).__name__}: {e}"
                if not any(m in text for m in TRANSPORT_ERRORS):
                    raise
                last = e
                wait_s = TRANSPORT_BACKOFF_S * (i + 1)
                print(f"    transport error on {label} "
                      f"(attempt {i+1}/{attempts}), retrying in {wait_s}s")
                print(f"      {text[:160]}")
                time.sleep(wait_s)
        raise SystemExit(f"{label} failed after {attempts} transport attempts: "
                         f"{last}")

    def write(self, fn, *args, value=0, quiet=False, finalized=False):
        """Send, wait, raise on anything that is not SUCCESS.

        Raises rather than returning a flag: every call site here treats a failed
        write as fatal, and a demo that printed a warning and carried on would
        report a verdict on a dispute that was never filed.

        `finalized=True` waits for FINALIZED instead of ACCEPTED. Needed by
        exactly one caller, `withdraw`, and for a measured reason: a value
        transfer's effect on `eth_getBalance` is **not visible at ACCEPTED**.
        Checked immediately after an accepted `withdraw`, the recipient's balance
        still reads its pre-transfer value and the contract still holds the bond;
        re-read minutes later, the contract is drained and the recipient is whole.
        So a demo that waited only for ACCEPTED would print `delta 0` and imply
        the payout failed. Costs ~70s.
        """
        t0 = time.time()
        status = (TransactionStatus.FINALIZED if finalized
                  else TransactionStatus.ACCEPTED)
        # Finalization is slower than acceptance by an order of magnitude, so it
        # gets a longer leash rather than the same one.
        interval = 5000 if finalized else WAIT_INTERVAL_MS
        retries = 90 if finalized else WAIT_RETRIES
        # Submit and wait are retried separately, and only for transport faults.
        # Once a hash exists the transaction is the network's business, so the
        # wait is resumed rather than the send repeated.
        tx = self._transport_retry(
            lambda: self.client.write_contract(
                address=self.address, function_name=fn, args=list(args),
                account=self.account, value=value),
            f"submit {fn}")
        receipt = self._transport_retry(
            lambda: self.client.wait_for_transaction_receipt(
                transaction_hash=tx, status=status,
                interval=interval, retries=retries),
            f"await {fn}")
        if not succeeded(receipt):
            raise SystemExit(
                f"{self.label}{fn} FAILED after {time.time()-t0:.0f}s\n"
                f"  {failure_detail(receipt)}")
        if not quiet:
            print(f"  {fn:16s} ok  {time.time()-t0:5.1f}s"
                  f"{'  (finalized)' if finalized else ''}")
        return receipt


def statement_hash(tab_id: str, cycle: int, notch_ids, legs) -> str:
    """Rebuild `close()`'s preimage and hash it, off-chain.

    A second implementation of `contracts/notch.py:370-373` **on purpose** —
    that is the whole point of a verifiable statement, and a shared helper would
    prove only that one function agrees with itself. `tests/direct/test_hash.py`
    pins the two together, so a drift in either is a red suite rather than a
    demo that quietly stops checking anything.

    The contract sorts `notches` and emits `legs` in sorted-key order with no
    spaces; both are reproduced here exactly, including `separators`.
    """
    import hashlib

    payload = json.dumps(
        {"tab": tab_id, "cycle": cycle, "notches": sorted(notch_ids),
         "legs": legs},
        sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def usdc(atto: int) -> str:
    """Atto to a readable USDC figure. Integer arithmetic only, no floats."""
    atto = int(atto)
    whole, frac = divmod(atto, 10**18)
    return f"{whole}.{frac:018d}".rstrip("0").rstrip(".") or "0"
